apiVersion: v1
kind: ConfigMap
metadata:
  name: sotetel-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.owner }}
  SPRING_DATASOURCE_URL: jdbc:postgresql://pg-rw:5432/{{ .Values.database.name }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.owner }}
  CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins }}